/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolnario;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Trie tr;
    public ArrayList<String> words;
    public ArrayList<String> meanings;
    
    public Form() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        words = new ArrayList<>();
        meanings = new ArrayList<>();
        tr = new Trie();
        System.out.println("Arbol inicializado...");
        this.TxtTree.setEditable(false);
        table();
    }
    
    public void table(){
        DefaultTableModel tb = new DefaultTableModel(){
              @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
        };
        tb.addColumn("Palabra");
        tb.addColumn("Significado");
        
        if(words.size() > 0){
        for(int i = 0 ; i < words.size(); i++){
            tb.addRow(new String[]{words.get(i),meanings.get(i)});
        }
        }
        
        this.ListaPalabras.setModel(tb);
        
    }
    
    public void buildLabels(){
        
        
            LinkedList<TrieNode> PreOrden = tr.getPreOrden();
            LinkedList<String> InOrden = tr.getInOrden();
            LinkedList<TrieNode> PosOrden = tr.getPostOrden();
            
            String pre = "PreOrden: ";
            String in = "InOrden: ";
            String pos = "PosOrden: ";
            
            for(TrieNode pr : PreOrden){
                pre += Character.toString(pr.content) + " ";
            }
            
            for(TrieNode po : PosOrden){
                pos += Character.toString(po.content) + " ";
            }
                        
            for(String i : InOrden){
                in += i + " ";
            }
            
            this.LblPreorden.setText(pre);
            this.LblInorden.setText(in);
            this.LblPosorden.setText(pos);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtTexto = new javax.swing.JTextField();
        BtnInsertar = new javax.swing.JButton();
        BtnRemover = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPalabras = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtTree = new javax.swing.JTextArea();
        LblPreorden = new javax.swing.JLabel();
        LblInorden = new javax.swing.JLabel();
        LblPosorden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnInsertar.setText("Insertar");
        BtnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertarActionPerformed(evt);
            }
        });

        BtnRemover.setText("Remover");
        BtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoverActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        ListaPalabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ListaPalabras);

        TxtTree.setColumns(20);
        TxtTree.setRows(5);
        jScrollPane2.setViewportView(TxtTree);

        LblPreorden.setText("PreOrden:");

        LblInorden.setText("InOrden:");

        LblPosorden.setText("PosOrden:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(LblPreorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblInorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtTexto)
                            .addComponent(BtnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(BtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LblPosorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPreorden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblInorden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPosorden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertarActionPerformed
        String word_to_insert = this.TxtTexto.getText();
        String[] splitted = word_to_insert.split(",");
        
        if(tr.search(splitted[0])){
            JOptionPane.showMessageDialog(null, "La palabra "+splitted[0]+" ya existe.", "Información", 2);   
        }
        else{
            tr.insert(splitted[0], splitted[1]);
            words.add(splitted[0]);
            meanings.add(splitted[1]);
            JOptionPane.showMessageDialog(null, "La palabra "+splitted[0]+" ha sido insertada.", "Información", 1);   
            this.table();
            this.buildLabels();
        }
        
        tr.getInOrden();
        System.out.println("");
        this.TxtTexto.setText("");
    }//GEN-LAST:event_BtnInsertarActionPerformed

    private void BtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoverActionPerformed
        String word_to_insert = this.TxtTexto.getText();
        String[] splitted = word_to_insert.split(",");
        
        if(tr.search(splitted[0])){
            tr.remove(splitted[0]);
            words.remove(splitted[0]);
            meanings.remove(splitted[1]);
            JOptionPane.showMessageDialog(null, "La palabra "+splitted[0]+" ha sido removida.", "Información", 1);
            this.table();
            this.buildLabels();
        }
        else{
            JOptionPane.showMessageDialog(null, "La palabra "+splitted[0]+" no existe.", "Información", 2);   
        }
        
        tr.getInOrden();
        System.out.println("");
        this.TxtTexto.setText("");
    }//GEN-LAST:event_BtnRemoverActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        String word_to_insert = this.TxtTexto.getText();
        String[] splitted = word_to_insert.split(",");
        if(tr.search(splitted[0])){
            JOptionPane.showMessageDialog(null, "La palabra "+splitted[0]+" existe.", "Información", 1);    
        }
        else{
            JOptionPane.showMessageDialog(null, "La palabra "+splitted[0]+" no existe.", "Información", 2); 
        }
        
    }//GEN-LAST:event_BtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnInsertar;
    private javax.swing.JButton BtnRemover;
    private javax.swing.JLabel LblInorden;
    private javax.swing.JLabel LblPosorden;
    private javax.swing.JLabel LblPreorden;
    private javax.swing.JTable ListaPalabras;
    private javax.swing.JTextField TxtTexto;
    private javax.swing.JTextArea TxtTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
