
package proyecto;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.JOptionPane;


public class EtapaFinal extends javax.swing.JFrame {

    private int turnos=20;
    private int tamaño;
    public EtapaFinal() {
       
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Endilch Bühne");
        this.jTextArea1.setEditable(false);
        this.jTextArea2.setEditable(false);
    }

        public void paint(Graphics a){
        super.paint(a);
        a.setColor(Color.WHITE);
        a.drawLine(100, 425, 130, 425);//1
        a.drawLine(140, 425, 170, 425);//2
        a.drawLine(180, 425, 210, 425);//3
        a.drawLine(220, 425, 250, 425);//4
        a.drawLine(260, 425, 290, 425);//5
        a.drawLine(300, 425, 330, 425);//6
        a.drawLine(340, 425, 370, 425);//7
        a.drawLine(380, 425, 410, 425);//8
        a.drawLine(420, 425, 450, 425);//9
        a.drawLine(460, 425, 490, 425);//10
        
        a.drawLine(550, 425, 580, 425);//11
        a.drawLine(590, 425, 620, 425);//12
        a.drawLine(630, 425, 660, 425);//13
        a.drawLine(670, 425, 700, 425);//14
        a.drawLine(710, 425, 740, 425);//15
        a.drawLine(750, 425, 780, 425);//16
        a.drawLine(790, 425, 820, 425);//17
        a.drawLine(830, 425, 860, 425);//18
        a.drawLine(870, 425, 900, 425);//19
        a.drawLine(910, 425, 940, 425);//20
        a.drawLine(950, 425, 980, 425);//21
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Letra = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        intentos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Derechos = new javax.swing.JMenu();
        DERECHOS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Small", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENDLICH BÜHNE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 45, 848, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENDLICH DUELL: LASS UNS GEHÄNGT SPIELEN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 112, 848, -1));

        Letra.setFont(new java.awt.Font("Sitka Small", 2, 12)); // NOI18N
        Letra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraActionPerformed(evt);
            }
        });
        getContentPane().add(Letra, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 400, 239, 35));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Small", 2, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("ACHT: DU HAST 20 VERSUCHE\nDAS KOMPLETT WORTE ZU FINDEN.\nWENN DU DAS WORTE ENTDECKEN\nNICHT VOR 10 VERSUCHE.\nDU MUSST ALLE WIEDER GANZ \nSPIELEN.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 165, 255, 123));

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Sitka Small", 2, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("VERFOLGEN: DAS WORT EINE \nKARRIERE AUS FRANCISCO\nJOSE DE CALDAS BEZIRK HÖSCHULE\nGEHORT\n(ALLES IST IN KLEINBUCHSTABEN\n GESCHREIBEN)");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 173, 250, 123));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KOMPLETT WORT (RABATTT SICH DREI VERSUCHE WENN DAS WORT FALSCH IST)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 446, 848, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Small", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BRIEF:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 378, 239, -1));

        jButton1.setFont(new java.awt.Font("Sitka Small", 2, 12)); // NOI18N
        jButton1.setText("FERTIG!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 468, 153, 53));

        intentos.setFont(new java.awt.Font("Sitka Small", 2, 12)); // NOI18N
        intentos.setForeground(new java.awt.Color(255, 255, 255));
        intentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(intentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 468, 285, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/85338.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 540));

        jMenu1.setText("Optionen");

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Salir.setText("Verlassen");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        Derechos.setText("Über auf");

        DERECHOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_MASK));
        DERECHOS.setText("Über auf");
        DERECHOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DERECHOSActionPerformed(evt);
            }
        });
        Derechos.add(DERECHOS);

        jMenuBar1.add(Derechos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Graphics b=getGraphics();
         b.setFont(new Font("Serif",Font.BOLD + Font.ITALIC,25));
        if(Letra.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Bitte, eintreten eine Brief oder eine Wort", "Versehen", JOptionPane.ERROR_MESSAGE);
        }else{
         tamaño=Letra.getText().length();
         if(tamaño==1){
         if(Letra.getText().equals("i")){  
           b.setColor(Color.WHITE);
           b.drawString("i", 115, 420);
           b.drawString("i", 315, 420);
           b.drawString("i", 435, 420);
           b.drawString("i", 885, 420);
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);
         }
         if(Letra.getText().equals("n")){
           b.setColor(Color.WHITE);
           b.drawString("n", 155, 420);
           b.drawString("n", 275, 420);
           b.drawString("n", 845, 420);
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);

         }
         if(Letra.getText().equals("g")){
           b.setColor(Color.WHITE);
           b.drawString("g", 195, 420); 
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);

         }
         if(Letra.getText().equals("e")){
           b.setColor(Color.WHITE);
           b.drawString("e", 235, 420);
           b.drawString("e", 355, 420);
           b.drawString("e", 565, 420);
           b.drawString("e", 645, 420);
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);

         }
         if(Letra.getText().equals("r")){
           b.setColor(Color.WHITE);
           b.drawString("r", 395, 420);
           b.drawString("r", 765, 420);
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);
         }
         if(Letra.getText().equals("a")){
           b.setColor(Color.WHITE);
           b.drawString("a", 475, 420);
           b.drawString("a", 965, 420);
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);
        
         }
         if(Letra.getText().equals("c")){
           b.setColor(Color.WHITE);
           b.drawString("c", 685, 420);
           b.drawString("c", 925, 420);
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);
         }
         if(Letra.getText().equals("t")){
           b.setColor(Color.WHITE);
           b.drawString("t", 725, 420); 
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);
         }
         if(Letra.getText().equals("l")){
           b.setColor(Color.WHITE);
           b.drawString("l", 605, 420); 
           turnos=turnos-1;
           intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);
         }
         if(Letra.getText().equals("o")){
           b.setColor(Color.WHITE);
           b.drawString("o", 805, 420);  
           turnos=turnos-1;
           JOptionPane.showMessageDialog(null, "Der brief steht in der Worte", "Richtig", JOptionPane.INFORMATION_MESSAGE);
            intentos.setText("Felhen: "+Integer.toString(turnos)+" turnos");
         }
         if(!Letra.getText().equals("i")&&!Letra.getText().equals("n")&&!Letra.getText().equals("g")&&!Letra.getText().equals("e")&&!Letra.getText().equals("r")&&!Letra.getText().equals("a")&&!Letra.getText().equals("l")&&!Letra.getText().equals("c")&&!Letra.getText().equals("t")&&!Letra.getText().equals("o")){
             JOptionPane.showMessageDialog(null, "Der brief steht nicht in der Worte", "Versuche es erneut", JOptionPane.ERROR_MESSAGE);
             turnos=turnos-1;
             intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");
         }
         }
         if(tamaño>=2){
             if(Letra.getText().equals("ingenieria electronica")){
           b.setColor(Color.WHITE);
           b.drawString("i", 115, 420);
           b.drawString("i", 315, 420);
           b.drawString("i", 435, 420);
           b.drawString("i", 885, 420);
           b.drawString("n", 155, 420);
           b.drawString("n", 275, 420);
           b.drawString("n", 845, 420);
           b.drawString("g", 195, 420);
           b.drawString("e", 235, 420);
           b.drawString("e", 355, 420);
           b.drawString("e", 565, 420);
           b.drawString("e", 645, 420);
           b.drawString("r", 395, 420);
           b.drawString("r", 765, 420);  
           b.drawString("a", 475, 420);
           b.drawString("a", 965, 420);
           b.drawString("c", 685, 420);
           b.drawString("c", 925, 420);    
           b.drawString("t", 725, 420); 
           b.drawString("l", 605, 420);   
           b.drawString("o", 805, 420);
           JOptionPane.showMessageDialog(null, "Du findest die Worte", "Glückwunsch!", JOptionPane.INFORMATION_MESSAGE);
           SeleccionarDificultad e = new SeleccionarDificultad();
           e.setVisible(true);
           dispose();
             }else{
             JOptionPane.showMessageDialog(null, "Es ist nicht die richtig Worte", "Versuche es ereneut", JOptionPane.ERROR_MESSAGE);
              turnos=turnos-3;
              intentos.setText("Fehlen: "+Integer.toString(turnos)+" dreht sich");    
             }
         } 

        }
         if(turnos<=0){
            JOptionPane.showMessageDialog(null, "VERSUCHE DER SPIEL ERNEUT", "DU SCHEITERN", JOptionPane.ERROR_MESSAGE);
            SeleccionarDificultad regresar=new SeleccionarDificultad();
            regresar.setVisible(true);
            regresar.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LetraActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    JOptionPane.showMessageDialog(null, "Oh Kurwa!, es ist unmöglich zu gehen","Oh Kurwa!!!",0);
    }//GEN-LAST:event_SalirActionPerformed

    private void DERECHOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DERECHOSActionPerformed

        JOptionPane.showMessageDialog(this,"Projekte erstellt für der Letze Qualifikation von POO 2018-3 ","Über auf",1);
        JOptionPane.showMessageDialog(this,"Autoren: Guillermo Velez, Sebastian Salinas","About of",1);
    }//GEN-LAST:event_DERECHOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtapaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtapaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtapaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtapaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtapaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DERECHOS;
    private javax.swing.JMenu Derechos;
    private javax.swing.JTextField Letra;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JLabel intentos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
