
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 28 07:42:00 COT 2021
//----------------------------------------------------

package SoloLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 41;
  public static final int Coma = 54;
  public static final int Llave_c = 48;
  public static final int Op_booleano = 44;
  public static final int Llave_a = 47;
  public static final int Unsigned = 30;
  public static final int If = 6;
  public static final int Void = 38;
  public static final int T_dato = 4;
  public static final int Default = 22;
  public static final int Numeral = 39;
  public static final int Dos_Puntos = 55;
  public static final int Else = 7;
  public static final int Cout = 37;
  public static final int Enum = 23;
  public static final int Break = 18;
  public static final int Goto = 25;
  public static final int Corchete_c = 50;
  public static final int Doble = 12;
  public static final int Corchete_a = 49;
  public static final int Extern = 24;
  public static final int Comentario_U = 60;
  public static final int Union = 28;
  public static final int Punto = 53;
  public static final int Parent_c = 46;
  public static final int Parent_a = 45;
  public static final int Return = 27;
  public static final int While = 9;
  public static final int Division = 17;
  public static final int Int = 11;
  public static final int Cadena = 5;
  public static final int For = 10;
  public static final int P_coma = 52;
  public static final int EOF = 0;
  public static final int Comentario_C = 59;
  public static final int Printf = 34;
  public static final int error = 1;
  public static final int Switch = 32;
  public static final int Comentario_A = 58;
  public static final int Linea = 2;
  public static final int Op_atribucion = 42;
  public static final int ERROR = 61;
  public static final int Do = 8;
  public static final int Continue = 21;
  public static final int Op_logico = 40;
  public static final int Case = 19;
  public static final int Short = 29;
  public static final int Register = 26;
  public static final int Scanf = 35;
  public static final int Const = 20;
  public static final int Identificador = 56;
  public static final int Cin = 36;
  public static final int Struct = 31;
  public static final int Resta = 15;
  public static final int Typedef = 33;
  public static final int Multiplicacion = 16;
  public static final int Op_incremento = 43;
  public static final int Numero = 57;
  public static final int Suma = 14;
  public static final int Main = 51;
  public static final int Igual = 13;
  public static final int Comillas = 3;
}

