/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author FliaSalinasRodriguez
 */
public class PrimeraVentana extends javax.swing.JFrame {

  private double valorvidas;
  private double valorpuntaje;
  private String usuarioactivo;
    
    public PrimeraVentana(double vv, double vp, String ua) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Project.exe :v");
        Inicio s=new Inicio();
        this.valorvidas=vv;
        this.valorpuntaje=vp;  
        this.usuarioactivo=ua;
        this.Texti.setText("Bienvenido "+usuarioactivo);
        this.VidasAsig.setText(valorvidas+"");
        this.PuntajeAsig.setText(valorpuntaje+"");
        this.TextoDescripcion.setEditable(false);        
   }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texti = new javax.swing.JLabel();
        LabelPuntaje = new javax.swing.JLabel();
        PuntajeAsig = new javax.swing.JLabel();
        LabelVidas = new javax.swing.JLabel();
        VidasAsig = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoDescripcion = new javax.swing.JTextArea();
        BtnAceptarInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Texti.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Texti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texti.setText("Jlabel1");
        Texti.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Texti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextiKeyReleased(evt);
            }
        });

        LabelPuntaje.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        LabelPuntaje.setText("Puntaje");

        PuntajeAsig.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        PuntajeAsig.setText("Pun");

        LabelVidas.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        LabelVidas.setText("Vidas");

        VidasAsig.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        VidasAsig.setText("Vd");

        TextoDescripcion.setColumns(20);
        TextoDescripcion.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        TextoDescripcion.setRows(5);
        TextoDescripcion.setText("Este programa consta de una serie de desafios\ncuya dificultad aumenta progresivamente. Usted\ncontará con un puntaje y vidas que a medida de \nque falle en un desafio, pierda una de estas.\n\nExisten 20 desafios, presione el boton aceptar de \nla parte inferior para continuar.\n");
        jScrollPane1.setViewportView(TextoDescripcion);

        BtnAceptarInicial.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        BtnAceptarInicial.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelPuntaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelVidas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PuntajeAsig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VidasAsig))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Texti, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnAceptarInicial)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPuntaje)
                    .addComponent(LabelVidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PuntajeAsig)
                    .addComponent(VidasAsig))
                .addGap(49, 49, 49)
                .addComponent(Texti, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAceptarInicial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TextiKeyReleased



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeraVentana(0,0,"").setVisible(true);
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarInicial;
    private javax.swing.JLabel LabelPuntaje;
    private javax.swing.JLabel LabelVidas;
    private javax.swing.JLabel PuntajeAsig;
    private javax.swing.JLabel Texti;
    private javax.swing.JTextArea TextoDescripcion;
    private javax.swing.JLabel VidasAsig;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
