/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author estudiantes
 */
public class FrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameModoC
     */
    public FrameInicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void close(){
        Object [] Op = {"Accept", "Cancel"};
        int eleccion = JOptionPane.showOptionDialog(null,"Are you sure to exit this app?","Confirm",JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,Op,"Accept");
        if(eleccion == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else{
            //do nothing :v
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        LblTitle = new javax.swing.JLabel();
        BtnModeA = new javax.swing.JButton();
        BtnModeB = new javax.swing.JButton();
        BtnModeC = new javax.swing.JButton();
        DescModeA = new javax.swing.JLabel();
        DescModeB = new javax.swing.JLabel();
        DescModeC = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MenuExit = new javax.swing.JMenu();
        ExitOption = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jEditorPane1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BtnModeA.setText("A Mode");
        BtnModeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModeAActionPerformed(evt);
            }
        });

        BtnModeB.setText("B Mode");
        BtnModeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModeBActionPerformed(evt);
            }
        });

        BtnModeC.setText("C Mode");
        BtnModeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModeCActionPerformed(evt);
            }
        });

        MenuExit.setText("File");

        ExitOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK));
        ExitOption.setText("Exit");
        ExitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOptionActionPerformed(evt);
            }
        });
        MenuExit.add(ExitOption);

        MenuBar.add(MenuExit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DescModeC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescModeB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescModeA, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnModeB)
                                .addComponent(BtnModeA)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(BtnModeC))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BtnModeA)
                .addGap(16, 16, 16)
                .addComponent(DescModeA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModeB)
                .addGap(11, 11, 11)
                .addComponent(DescModeB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnModeC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DescModeC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOptionActionPerformed
        close();
    }//GEN-LAST:event_ExitOptionActionPerformed

    private void BtnModeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModeAActionPerformed
        FrameModoA e = new FrameModoA();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnModeAActionPerformed

    private void BtnModeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModeBActionPerformed
        FrameModoB e = new FrameModoB();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnModeBActionPerformed

    private void BtnModeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModeCActionPerformed
        FrameModoC e = new FrameModoC();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnModeCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModeA;
    private javax.swing.JButton BtnModeB;
    private javax.swing.JButton BtnModeC;
    private javax.swing.JLabel DescModeA;
    private javax.swing.JLabel DescModeB;
    private javax.swing.JLabel DescModeC;
    private javax.swing.JMenuItem ExitOption;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuExit;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
