/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import huffmancera.HuffmanLib;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;

 class Panelin extends javax.swing.JPanel {
    public HuffmanLib huf;
    /**
     * Creates new form Panelin
     */
    public Panelin() {
        initComponents();
    }
    /**
     * Creates new form Panelin
     */
    public Panelin(HuffmanLib huf) {
        this.huf = huf;
        initComponents();
    }

    public void setHuf(HuffmanLib huf) {
        this.huf = huf;
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        if (this.huf==null){
            return;
        }
        int n = 0;
        for (int i = 0; i<huf.Tablas.get(huf.Tablas.size()-1).cars.size();i++){
            if (huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).length()>n){
                n=huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).length();
            }
        }
        int m=20;
        g.setFont(new Font(Font.SERIF, Font.BOLD, 11));
        for (int i = 0; i < huf.Tablas.get(huf.Tablas.size()-1).cars.size();i++){
            int prev=(int)Math.pow(1.955, n);
            g.setColor(Color.blue);
            g.fillOval(prev*m - 1, 0 , 30, 30);
            g.setColor(Color.white);  
            g.drawString(Integer.toString(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(huf.calcularN()-1).frec), m*prev+5, 20); //Raíz

            int acT = huf.calcularN()-1;
            for (int j = 0; j < huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).length(); j++){
                int t = prev;
                if ("1".equals(huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).cars.get(i)).split("")[j])){
                    prev += Math.pow(2,(n-(j+1)));
                    acT=huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).hidjoder;
                }else{
                    prev -= Math.pow(2,(n-(j+1)));
                    acT=huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).hidjoizq;
                }
                g.setColor(Color.black);  
                g.drawLine((t*m)+20, m*j+20, m*prev+20, m*(j+1)+20); //Lineas
                
                if (!huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).cad.equals("")){ //Hojas
                    g.setColor(Color.red);
                    g.fillOval(m*prev+5, m*(j+1)+10, 25,25);
                    g.setColor(Color.white);
                    
                    g.drawString(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).cad, m*prev+15, m*(j+1)+30); 
                    g.setColor(Color.black);  
                    g.drawString(huf.crips.get(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).cad), m*prev+10, m*(j+1)+55);
                }else{
                    g.setColor(Color.blue);
                    g.fillOval(m*prev, m*(j+1),30,30);
                    g.setColor(Color.white);  
                    g.drawString(Integer.toString(huf.Tablas.get(huf.Tablas.size()-1).Colas.get(acT).frec), m*prev+10, m*(j+1)+20);//Nodos
                }
            }
        }
        this.setPreferredSize(new Dimension((int)(Math.pow(2,n+1))*m, (n+2)*m));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 240, 250));
        setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
